### ISSUE TITLE
Working around a Certificate Exception

### ISSUE THREAD

**Issue by anothrNick** [allcolor/YaHP-Converter#11]
Is there any way for me to work around a certificate exception. I am trying to pass the URL of a webpage to YaHP but, because the certificate cannot be verified, I get an exception and YaHP fails to make the conversion. Any ideas?

Thanks in advance, and besides this issue, YaHP Converter has been great!

**Comment by allcolor** [comment]
Hi, I think you can use the solution below from so_mv.

http://stackoverflow.com/questions/1219208/is-it-possible-to-get-java-to-ignore-the-trust-store-and-just-accept-whatever

Regards,
Quentin

2013/8/20 Nick Sjostrom notifications@github.com

> Is there any way for me to work around a certificate exception. I am
> trying to pass the URL of a webpage to YaHP but, because the certificate
> cannot be verified, I get an exception and YaHP fails to make the
> conversion. Any ideas?
> 
> Thanks in advance, and besides this issue, YaHP Converter has been great!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/11
> .

## 

All those moments will be lost in time, like tears in rain.

**Comment by anothrNick** [comment]
Thanks for the quick response.

Yep, a similar solution worked! Thanks a lot!
