### ISSUE TITLE
Relative output path

### ISSUE THREAD

**Issue by anothrNick** [allcolor/YaHP-Converter#12]
Hi again,

I was also wondering if there was a way to make YaHP work with a relative output path rather than an absolute one.

Thanks

**Comment by allcolor** [comment]
Hi,

In the code (class CYahpConverter), you give an outputstream to the method,
the way you construct it is up to you. If you're talking about
CSimpleConversion, this code is meant as an usage example...

Regards,
Quentin

2013/8/23 Nick Sjostrom notifications@github.com

> Hi again,
> 
> I was also wondering if there was a way to make YaHP work with a relative
> output path rather than an absolute one.
> 
> Thanks
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/12
> .

## 

All those moments will be lost in time, like tears in rain.

**Comment by anothrNick** [comment]
I realized my issue is because I'm trying to create the pdf from a jsp servlet and it doesn't accept a relative url.
