### ISSUE TITLE
Overlapping text while converting html to pdf using yahp-v1.2.20c

### ISSUE THREAD

**Issue by venkatakarthikj** [allcolor/YaHP-Converter#13]
Hi....i am trying to convert html to pdf using yahp-v1.2.20c.....html file contains <span> ,<div> elements and tables........while converting  <span> and <div> elements data overlapping with tables.....means data moving up and overlapping with tables....i am placing <span> and <div> elements some times before tables and some times after tables........i tried in so many ways to solve........please help me.......thanks in advance...........

**Comment by allcolor** [comment]
Hi,

could you send me a sample html showing the problem (with all needed
related files like css/images).

Regards,
Quentin

2013/9/11 venkatakarthikj notifications@github.com

> Hi....i am trying to convert html to pdf using yahp-v1.2.20c.....html file
> contains ,
> elements and tables........while converting and
> elements data overlapping with tables.....means data moving up and
> overlapping with tables....i am placing and
> elements some times before tables and some times after tables........i
> tried in so many ways to solve........please help me.......thanks in
> advance...........
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/13
> .

## 

All those moments will be lost in time, like tears in rain.

**Comment by venkatakarthikj** [comment]
Hi,

This is sample html:
<html>
<body>

<table><tr>
<td>
<span>test1</span>
<span>test2</span>
<table><tr><td>check1</td><td>check2</td></tr></table>
<span>test3</span>
<span>test4</span>
</td>
<td>
<span>test5</span>
<span>test6</span>
<table><tr><td>check3</td><td>check4</td></tr></table>
<span>test7</span>
<span>test8</span>
</td>
</tr>
</table>

span elements are overlapping with table............

**Comment by venkatakarthikj** [comment]
Test3 & Test4, Test7 & Test8 are overlapping with table.....

**Comment by allcolor** [comment]
Hi,

I've tested with the following html:

<html>
  <head></head>
  <body>

<table border="1"><tbody><tr>
<td>
test1
test2
<table border="1"><tbody><tr>
<td>check1</td>
<td>check2</td>
</tr></tbody></table>test3
test4
</td>
<td>
test5
test6
<table><tbody><tr>
<td>check3</td>
<td>check4</td>
</tr></tbody></table>test7
test8
</td>
</tr></tbody></table>

  </body>
</html>

The rendering is correct... can't see your problem. Also github is not good
to transmit like you did an html file. If you feel there is a problem,
please send me at

"quentin.anciaux@allcolor.org" your html file/css etc for me to test.

Regards,
Quentin

2013/9/12 venkatakarthikj notifications@github.com

> Test3 & Test4, Test7 & Test8 are overlapping with table.....
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/13#issuecomment-24298460
> .

## 

All those moments will be lost in time, like tears in rain.

**Comment by venkatakarthikj** [comment]
K....Thank u so much... i will check once again...let u know

**Comment by venkatakarthikj** [comment]
I solved issue by removing all span and div elements, placing data inside table.......Thanks for ur reply.....
