### ISSUE TITLE
Textarea width does not work

### ISSUE THREAD

**Issue by tamnguyenminh** [allcolor/YaHP-Converter#15]
Hi Mr Quentin,

I'm using your YaHP to export pdf but the exported pdf doesn't reflect my html correctly with Textarea. Does exported text are have fixed width or there are some thing wrong from my html (It's very simple). Please help.

Thanks in advanced
Tam Nguyen Minh

I'm sorry. I don't know how to add code to this issue so I take a screenshot of it.

![htmlcode](https://f.cloud.github.com/assets/5804724/1434006/41ab2fe6-4109-11e3-9431-e1ea88546b1e.jpg)

![exportedpdf](https://f.cloud.github.com/assets/5804724/1433995/6a644824-4108-11e3-9e15-45cf741eac29.jpg)

**Comment by allcolor** [comment]
Hi,

try setting the width in cm instead of '%', and do not set cols
attribute... or do not use a textarea, and use a div with a border instead.

Regards,
Quentin

2013/10/30 tamnguyenminh notifications@github.com

> Hi Mr Quentin,
> 
> I'm using your YaHP to export pdf but the exported pdf doesn't reflect my
> html correctly with Textarea. Does exported text are have fixed width or
> there are some thing wrong from my html (It's very simple). Please help.
> textarea.textarea { background:#fff; border-bottom:1px solid #ddd;
> border-left:1px solid #c3c3c3; border-right:1px solid #c3c3c3;
> border-top:1px solid #7c7c7c; color:#333; font-family:Arial, Helvetica,
> Tahoma, Verdana, sans-serif; font-size:100%; margin:0; width:99%;
> resize:none; } textarea.small { height:5.5em; resize:none; }
> textarea.medium { height:10em; resize:none; } textarea.large { height:20em;
> resize:none; }
> 
> filed 1
> filed 2
> 
> [image: exportedpdf]https://f.cloud.github.com/assets/5804724/1433995/6a644824-4108-11e3-9e15-45cf741eac29.jpg
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/15
> .

## 

All those moments will be lost in time, like tears in rain.

**Comment by tamnguyenminh** [comment]
Thank you, Quentin. I still can't get the right textarea with cm (and without cols), but div with a border is a brilliant idea. I also add p tag to make my document looks nicer.
