### ISSUE TITLE
Image is not coming into the PDF !!

### ISSUE THREAD

**Issue by pankz709** [allcolor/YaHP-Converter#19]
Hi,

Converter is working fine for me except the image is not coming into the pdf.

In my Source code image is is in base 64 format like this img name="digTechSigIMG" src="data:image/gif;base64.....

While generating the pdf image is not coming.

Please help !!

**Comment by allcolor** [comment]
Images in base64 are not supported. You have to use images in files... The
url pointing to the image can be relative to the base url given to the
convert function or an absolute url. (can be any URL supported by java, ie:
file:// http:// etc)

Regards,
Quentin

2014/1/3 pankz709 notifications@github.com

> Hi,
> 
> Converter is working fine for me except the image is not coming into the
> pdf.
> 
> In my Source code image is is in base 64 format like this img
> name="digTechSigIMG" src="data:image/gif;base64.....
> 
> While generating the pdf image is not coming.
> 
> Please help !!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/19
> .

## 

All those moments will be lost in time, like tears in rain. (Roy
Batty/Rutger Hauer)
