### ISSUE TITLE
I have problems when I use Dojo charts . I can't get the chart in the PDF

### ISSUE THREAD

**Issue by Jorgealb01** [allcolor/YaHP-Converter#20]
I can not get the chart in the pdf file when I use dojo charts .. Is this supported?

**Comment by allcolor** [comment]
Javascript is not interpreted... If you want a chart, you have to create an
image and reference it via an <img tag...

Regards,
Quentin

2014/1/15 Jorgealb01 notifications@github.com

> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/20
> .

## 

All those moments will be lost in time, like tears in rain. (Roy
Batty/Rutger Hauer)

**Comment by Jorgealb01** [comment]
OK thk for your help .... I will do that

Date: Wed, 15 Jan 2014 02:08:19 -0800
