### ISSUE TITLE
How to link CSS?

### ISSUE THREAD

**Issue by Wizzpro** [allcolor/YaHP-Converter#24]
Hi! I have problems converting an HTML-file where there is a style-tag or link to a CSS-file. 
How can I solve this?

Regards, 

Oliver

**Comment by allcolor** [comment]
Hi,  the css needs only to be referred with a valid href,  either relative
to the base url or with an absolute url.

Regards.

**Comment by Wizzpro** [comment]
Thank you for your reply, it works with a valid href. But my next question is this, is it possible to link css through an url this way: src:url(http://www.supersavertravel.se/system/fonts/RobotoCondensed-Light-webfont.eot)? I´m having issues with this kind of bindings. 
Thank you.

**Comment by allcolor** [comment]
there is no support for web font.  If you need special font you need ttf
font and embed them in the pdf.

**Comment by Wizzpro** [comment]
Ok thank you.
