### ISSUE TITLE
Page Break "<yahp:pb />" breaks the conversion process

### ISSUE THREAD

**Issue by varun-prathap** [allcolor/YaHP-Converter#34]
Hi, 

YaHP-Converter has been working like a charm for quite sometime. Now that when I try to enhance the PDF (include page breaks in markup using "yahp:pb"), the converter fails with the below exception stacktrace, 

Exception in thread "main" org.allcolor.yahp.converter.IHtmlToPdfTransformer$CConvertException: ERROR: An unhandled exception occured: null
    at org.allcolor.yahp.cl.converter.CHtmlToPdfFlyingSaucerTransformer.transform(CHtmlToPdfFlyingSaucerTransformer.java:791)
    at org.allcolor.yahp.converter.CYaHPConverter.convertToPdf(CYaHPConverter.java:172)
    at PDFGenerator.generatePDFFile(PDFGenerator.java:70)
    at PDFGenerator.main(PDFGenerator.java:25)
Caused by: java.lang.NullPointerException
    at org.allcolor.yahp.cl.converter.CHtmlToPdfFlyingSaucerTransformer.transform(CHtmlToPdfFlyingSaucerTransformer.java:652)
    ... 3 more
Destroying YAHP ClassLoader Tree

I've tried adding the page-break tag at multiple places but every time I get back the above exception stacktrace. I'm using the latest library (yahp-v1.3). Please suggest. Thanks.

**Comment by allcolor** [comment]
Hi,

Maybe your html is invalid... at the line 652, yahp try to access the
<body> of the page...

as it is a nullpointer, seems the body is missing... that could mean you
put the page break outside the body, which is invalid.

Regards,
Quentin Anciaux

2015-06-08 22:13 GMT+02:00 varun-prathap notifications@github.com:

> Hi,
> 
> YaHP-Converter has been working like a charm for quite sometime. Now that
> when I try to enhance the PDF (include page breaks in markup using ""), the
> converter fails with the below exception stacktrace,
> 
> Exception in thread "main"
> org.allcolor.yahp.converter.IHtmlToPdfTransformer$CConvertException: ERROR:
> An unhandled exception occured: null
> at
> org.allcolor.yahp.cl.converter.CHtmlToPdfFlyingSaucerTransformer.transform(CHtmlToPdfFlyingSaucerTransformer.java:791)
> at
> org.allcolor.yahp.converter.CYaHPConverter.convertToPdf(CYaHPConverter.java:172)
> at PDFGenerator.generatePDFFile(PDFGenerator.java:70)
> at PDFGenerator.main(PDFGenerator.java:25)
> Caused by: java.lang.NullPointerException
> at
> org.allcolor.yahp.cl.converter.CHtmlToPdfFlyingSaucerTransformer.transform(CHtmlToPdfFlyingSaucerTransformer.java:652)
> ... 3 more
> Destroying YAHP ClassLoader Tree
> 
> I'm using the latest library (yahp-v1.3). Please suggest. Thanks.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/allcolor/YaHP-Converter/issues/34.

## 

All those moments will be lost in time, like tears in rain. (Roy
Batty/Rutger Hauer)

**Comment by varun-prathap** [comment]
Thank you, this 'meta' tag was causing the issue, 
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
