### ISSUE TITLE
Identifier of converting completely

### ISSUE THREAD

**Issue by milkdeliver** [allcolor/YaHP-Converter#37]
Hi,
I looked into the API of **Converter** but do not find a `Identifier` that could explicitly tell us the converter process has been completed.Do I skip something?Thank you for your help.

Best regards

**Comment by allcolor** [comment]
Hi,

I don't understand your question. The process is completed when the method
returns a handle to the PDF file, or throws an exception because it cannot
convert it.

Regards

2015-08-11 10:46 GMT+02:00 Milkdelivery notifications@github.com:

> Hi,
> I looked into the API of _Converter_ but do not find a Identifier that
> could explicitly tell us the converter process has been completed.Do I skip
> something?Thank you for your help.
> 
> Best regards
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/allcolor/YaHP-Converter/issues/37.

## 

All those moments will be lost in time, like tears in rain. (Roy
Batty/Rutger Hauer)

**Comment by milkdeliver** [comment]
Hi,

Sorry to confuse you.Try to make it clearly.

> **Converter** transformed the `html` to `pdf` then need to have a response to the client side which tells the font-end the process has been done.

**Comment by allcolor** [comment]
But you call it from java, when the method returns the handle to the file,
the conversion is done... I still don't understand the question.

Regards,
Quentin

2015-08-12 11:05 GMT+02:00 Milkdelivery notifications@github.com:

> Hi,
> 
> Sorry to confuse you.Try to make it clearly.
> 
> _Converter_ transformed the html to pdf then need to have a response to
> the client side which tells the font-end the process has been done.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/allcolor/YaHP-Converter/issues/37#issuecomment-130224665
> .

## 

All those moments will be lost in time, like tears in rain. (Roy
Batty/Rutger Hauer)

**Comment by milkdeliver** [comment]
Finally I solved it. Thank you Quentin with so much patience.
