### ISSUE TITLE
 What are the advantages of using this library over IText

### ISSUE THREAD

**Issue by EllenJ** [allcolor/YaHP-Converter#43]
What are the advantages and disadvantages of using this library over Itext

**Comment by allcolor** [comment]
Hi,

It's lgpl and it works... it also uses itext; it has facility to handle
page break and header/footer.

Disavantages: the project is no more active, I only answer emails and gives
workaround/support if needed, but I won't make new version, or correct
bugs. So the project is as is, if it's useful to you, great.

Regards

2016-03-31 18:11 GMT+02:00 EllenJ notifications@github.com:

> What are the advantages and disadvantages of using this library over Itext
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> https://github.com/allcolor/YaHP-Converter/issues/43

## 

All those moments will be lost in time, like tears in rain. (Roy
Batty/Rutger Hauer)
