### ISSUE TITLE
Not showing image in pdf

### ISSUE THREAD

**Issue by janakjoshi** [allcolor/YaHP-Converter#6]
HI,
I am using yahp library, generating PDF from HTML I can see image in HTML but
Not showing image in pdf.

**Comment by allcolor** [comment]
Hi,

do you correctly set the base url of your image ? If yes, could you try by
setting an absolute url to your images ?

Like

<img src="http://host:port/path/to/image" />

or

<img src="file:///path/to/image" />

Regards,
Quentin

2013/1/23 janakjoshi notifications@github.com

> HI,
> I am using yahp library, generating PDF from HTML I can see image in HTML
> but
> Not showing image in pdf.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/6.

## 

All those moments will be lost in time, like tears in rain.

**Comment by janakjoshi** [comment]
hi, thanks for reply  my HTML has  this image tag & image is there in location.
 < img src="D:/sanitize/logo.JPG" border="0" height="70"width="200" /> 

## Following is my java Code

```
        CYaHPConverter converter = new CYaHPConverter();
        FileOutputStream out = new FileOutputStream(new File("D:/sanitize/x.pdf"));
        Map properties = new HashMap();
        List headerFooterList = new ArrayList();
        properties.put(IHtmlToPdfTransformer.PDF_RENDERER_CLASS,
                IHtmlToPdfTransformer.DEFAULT_PDF_RENDERER);

        converter.convertToPdf(strHtml,
            IHtmlToPdfTransformer.A4P, headerFooterList, "file://c:/temp/", out,
            properties);
        out.flush();
        out.close();
```

**Comment by allcolor** [comment]
Hi, your src is not correct.... an URL must have a protocol, in your case
you should have:

<img src="file:///D:/sanitize/logo.JPG" border="0" height="70"width="200"
/>

Regard,
Quentin

2013/1/23 janakjoshi notifications@github.com

> hi, thanks for reply my HTML has this image tag & image is there in
> location.
> < img src="D:/sanitize/logo.JPG" border="0" height="70"width="200" />
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/6#issuecomment-12586089.

## 

All those moments will be lost in time, like tears in rain.

**Comment by janakjoshi** [comment]
Hey , Thanks a lot. its worked.
Thank you very much.

**Comment by pankz709** [comment]
Hi,

Converte is working fine for me except the image is not coming into the pdf.

In my Source code image is is in base 64 format like this img name="digTechSigIMG" src="data:image/gif;base64.....

While generating the pdf image is not coming.

Please help !!

**Comment by allcolor** [comment]
Image in base64 are not supported. You have to use images in files... The
url pointing to the image can be relative to the base url given to the
convert function or an absolute url. (can be any URL supported by java, ie:
file:// http:// etc)

Regards,
Quentin

2014/1/3 pankz709 notifications@github.com

> Hi,
> 
> Converte is working fine for me except the image is not coming into the
> pdf.
> 
> In my Source code image is is in base 64 format like this img
> name="digTechSigIMG" src="data:image/gif;base64.....
> 
> While generating the pdf image is not coming.
> 
> Please help !!
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/allcolor/YaHP-Converter/issues/6#issuecomment-31519314
> .

## 

All those moments will be lost in time, like tears in rain. (Roy
Batty/Rutger Hauer)

**Comment by milkdeliver** [comment]
img with url can't not be included in the pdf.Could you give me a suggestion?

``` css
<img src="http://www.zenefits.com/static/marketing/img/carriers/img.jpg" alt="Capture.jpg">
```

**Comment by allcolor** [comment]
It does work,  make sure you can display it locally. Download it and
replace with a local file:/// link.

Regards

**Comment by milkdeliver** [comment]
Does it only convert local resources?

**Comment by allcolor** [comment]
No, but it has to have access to the resource, if the remote server check
for a specific user agent or a cookie it might not work. If it work locally
and not with the remote server, that means the server does not return the
image or does not return the correct mimetype.

Regards

**Comment by milkdeliver** [comment]
- The page displays right at local with remote url.
  `<img src="http://www.zenefits.com/static/marketing/img/carriers/img.jpg" alt="Capture.jpg">`
- The remote url is public resource which anyone can access
- MIME is img type that means could be used in `<img>` tag.

Now the problem still raise.Could you give me a clue?

**Comment by allcolor** [comment]
So as I say,  does it work with a file url with the same image? If it does
then either the remote server does not return an image mimetype in the
content-type http header,  or the server does not return the image if a
certain cookie is not present,  or the server does not return the image if
a certain user agent is not used, or the server takes too long to send it
and there is a timeout.

That a browser is able to display it is irrelevant. First ensure it does
work locally, then if it does, try to download the image in java, using a
java Url object.

Regards

**Comment by sayhello2ashutosh** [comment]
YAHP api is taking 30-45 seconds to generate PDF first time. After that it is taking less time to generate pdf.
Any clue or any help Why it is taking too much time first time.

**Comment by allcolor** [comment]
Class loading occurs the first time, but again you should not use the
builtin classloader inside an application server.

Just put the following jar in the WEB-INF/lib:

https://bintray.com/artifact/download/allcolor/alc-web/org/allcolor/shaniparser/1.4.22/shaniparser-1.4.22.jar
https://bintray.com/artifact/download/allcolor/alc-web/org/allcolor/shaniparser-xmlapi/1.4.22/shaniparser-xmlapi-1.4.22.jar
https://bintray.com/artifact/download/allcolor/alc-web/org/allcolor/yahp/1.3a/yahp-1.3a.jar
https://bintray.com/artifact/download/allcolor/alc-web/org/allcolor/yahp-core-renderer/1.3/yahp-core-renderer-1.3.jar
https://bintray.com/artifact/download/allcolor/alc-web/org/allcolor/yahp-internal/1.3/yahp-internal-1.3.jar
https://bintray.com/artifact/download/allcolor/alc-web/org/allcolor/yahp-itext/1.3/yahp-itext-1.3.jar
https://bintray.com/artifact/download/allcolor/alc-web/org/allcolor/yahp-tidy/1.3/yahp-tidy-1.3.jar
http://central.maven.org/maven2/jaxen/jaxen/1.1.6/jaxen-1.1.6.jar

This version does not use anymore the classloader. Just put an instance
of CYaHPConverter in the servletcontext, and share it. The class is
threadsafe.

Regards

2016-03-30 8:44 GMT+02:00 sayhello2ashutosh notifications@github.com:

> YAHP api is taking 30-45 seconds to generate PDF first time. After that it
> is taking less time to generate pdf.
> Any clue or any help ahy it is taking too much time first time.
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/allcolor/YaHP-Converter/issues/6#issuecomment-203277356

## 

All those moments will be lost in time, like tears in rain. (Roy
Batty/Rutger Hauer)

**Comment by sayhello2ashutosh** [comment]
Thanks!..will load  with above jars and let you know..if it is working fine or not.

**Comment by sayhello2ashutosh** [comment]
I have html content having data in hindi/chineese, but when i am trying to generate pdf through YAHP, generated pdf shows only english content and hindi/chineese content get disappeared.

i have set http response's content type to utf-8 but it didn't work.
Any help on this will be appreciated.

**Comment by allcolor** [comment]
Hi, you have to use a unicode font like arial unicode and embed it.
Regards

Le 23 août 2016 21:57, "sayhello2ashutosh" notifications@github.com a
écrit :

**Comment by arunzz** [comment]
Image inside a table td is not coming up in pdf. If its outside its coming up , pls help.
<td colspan='4' rowspan='2' class='hideprops'><img src=\"arunkumar/Desktop/save.gif\" style='width: 80px' alt=''/></td>
